-- Seed thêm phim mới vào database
INSERT INTO movies (title, description, duration_minutes, poster_url, banner, genre, release_date, director, cast_members, age_rating, rating, status) VALUES
('Tạm Biệt Gohan', 'Câu chuyện cảm động về tình bạn giữa một chú chó trung thành và người chủ của mình qua nhiều năm tháng.', 140, 'https://m.media-amazon.com/images/M/MV5BM2E0ZDBkNGItNTk2ZS00MzFjLTllMTEtNjE4MzljOGYzNTBkXkEyXkFqcGc@._V1_.jpg', 'https://m.media-amazon.com/images/M/MV5BM2E0ZDBkNGItNTk2ZS00MzFjLTllMTEtNjE4MzljOGYzNTBkXkEyXkFqcGc@._V1_.jpg', 'Tình cảm, Gia đình', '2026-05-15', 'Takashi Yamazaki', 'Sota Fukushi, Mina Fujii', 'P', 8.2, 'showing'),
('Heo Năm Móng', 'Hành trình kỳ diệu của chú heo năm móng vượt qua mọi thử thách để tìm lại gia đình.', 103, 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg', 'https://image.tmdb.org/t/p/original/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg', 'Hoạt hình, Phiêu lưu', '2026-04-30', 'Nguyễn Quang Dũng', 'Trấn Thành, Trường Giang, Thu Trang', 'P', 7.5, 'showing'),
('Ma Da Hàn Quốc', 'Những sự kiện bí ẩn xảy ra tại một ngôi làng cổ Hàn Quốc khi linh hồn trả thù trỗi dậy.', 95, 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg', 'https://image.tmdb.org/t/p/original/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg', 'Kinh dị, Tâm lý', '2026-05-13', 'Park Chan-wook', 'Song Kang-ho, Jeon Do-yeon', 'T18', 7.8, 'showing'),
('Anh Hùng', 'Lối đi của những anh hùng thầm lặng hy sinh vì Tổ quốc từ thời kỳ thiên niên kỷ.', 125, 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7GGHK1RQhp6r.jpg', 'https://image.tmdb.org/t/p/original/vZloFAK7NmvMGKE7GGHK1RQhp6r.jpg', 'Hành động, Lịch sử', '2026-04-24', 'Zhang Yimou', 'Jet Li, Tony Leung, Maggie Cheung', 'T13', 8.0, 'showing'),
('Đại Tiệc Trăng Máu', 'Một bữa tiệc sinh nhật biến thành ác mộng khi bí mật động trời của mọi người bị phơi bày.', 110, 'https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg', 'https://image.tmdb.org/t/p/original/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg', 'Kinh dị, Giật gân', '2026-04-24', 'Nguyễn Hữu Hoàng', 'Kaity Nguyễn, Kiều Minh Tuấn', 'T16', 7.3, 'showing'),
('Phi Công', 'Câu chuyện về một phi công trẻ vượt qua nghịch cảnh và nỗi sợ hãi để trở thành huyền thoại bầu trời.', 135, 'https://image.tmdb.org/t/p/w500/62HCnUTziyWQpITMq25QVP7MBO6.jpg', 'https://image.tmdb.org/t/p/original/62HCnUTziyWQpITMq25QVP7MBO6.jpg', 'Hành động, Phiêu lưu', '2026-06-01', 'Joseph Kosinski', 'Tom Cruise, Miles Teller', 'T13', 8.7, 'coming'),
('Doraemon: Vùng Đất Lý Tưởng Trên Bầu Trời', 'Nobita và Doraemon cùng nhóm bạn phiêu lưu tìm vùng đất lý tưởng trên bầu trời.', 108, 'https://image.tmdb.org/t/p/w500/8GnWDLn2AhnmkQ7hqY9gCPFcKlR.jpg', 'https://image.tmdb.org/t/p/original/8GnWDLn2AhnmkQ7hqY9gCPFcKlR.jpg', 'Hoạt hình, Gia đình', '2026-06-10', 'Takumi Doyama', 'Wasabi Mizuta, Megumi Ohara', 'P', 7.9, 'coming'),
('Lật Mặt 8: Vòng Tay Nắng', 'Tình cảm gia đình và những bí mật được phơi bày trong hành trình tìm lại ký ức của một người con gái.', 128, 'https://image.tmdb.org/t/p/w500/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg', 'https://image.tmdb.org/t/p/original/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg', 'Tình cảm, Gia đình', '2026-04-25', 'Lý Hải', 'Trấn Thành, Ốc Thanh Vân, Mạc Văn Khoa', 'T13', 8.1, 'showing');
